- id: '1711548521595'
  alias: Frontdoor Snapshot Notification
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      camera: camera.door_bell
      notify_device: b457d6c1bbed3d192a7deb91c32ab191
      delay: 3
      motion_sensor: binary_sensor.door_bell_motion
      notification_title: Front Door Motion detected!
- id: '1711548684986'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.notify
        metadata: {}
        data:
          message: '{{sensors}}'
      exclude:
        entity_id:
        - sensor.emily_pixel_battery_level
        - sensor.joyce_phone_battery_level
        - sensor.sean_pixel_battery_level
- id: '1711548743791'
  alias: Back Door Snapshot Notification
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      motion_sensor: binary_sensor.blink_back_door_motion_detected
      camera: camera.blink_back_door
      notify_device: b457d6c1bbed3d192a7deb91c32ab191
      notification_title: Back Door Motion detected!
      delay: 3
