homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
      allow_bypass_login: true
    - type: legacy_api_password
      api_password: !secret api_password
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 338
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

map:

zone:
  - name: home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 175

proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.sean_pixel_3
      - device_tracker.emily_pixel_3
    tolerance: 100
    unit_of_measurement: mi

cloud:

mobile_app:

circadian_lighting:

hacs:
  token: !secret hacs_token

system_health:

lovelace:
  mode: yaml

frontend:
  themes: !include_dir_merge_named themes

config:
http:
  base_url: !secret base_url

updater:

# Discover some devices automatically
discovery:
  ignore:
#    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
    entities:
      - group.sean
      - group.emily
      - light.bathroom
      - light.bedroom
      - light.living_room
      - light.office
      - sensor.living_room_thermostat_hvac_state
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.bedroom_temp
      - sensor.bathroom_temperature_f
      - sensor.dark_sky_temperature
      - sensor.sun_elevation
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_precip_probability
      - sensor.illumination_158d0002047afe
      - sensor.illumination_158d000237a64a
      - sensor.bedroom_humidity
      - sensor.office_lux
      - sensor.living_room_thermostat_humidity
      - sensor.processor_use
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.office_motion_sensor_temperature
      - sensor.bathroom_sensor_temperature
      - sensor.living_room_temperature_f
      - sensor.sean_room_location
      - sensor.emily_room_location

recorder:
  purge_keep_days: 3
  auto_purge: true
  include:
    domains:
      - switch
    entities:
      - group.sean
      - group.emily
      - light.bathroom
      - light.bedroom
      - light.living_room
      - light.office
      - sensor.living_room_thermostat_hvac_state
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.bedroom_temp
      - sensor.bathroom_temperature_f
      - sensor.dark_sky_temperature
      - sensor.sun_elevation
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_precip_probability
      - sensor.illumination_158d0002047afe
      - sensor.illumination_158d000237a64a
      - sensor.bedroom_humidity
      - sensor.office_lux
      - sensor.living_room_thermostat_humidity
      - sensor.processor_use
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.office_motion_sensor_temperature
      - sensor.bathroom_sensor_temperature
      - sensor.living_room_temperature_f

# View all events in a logbook
logbook:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily
  - platform: openweathermap
    api_key: !secret openweather_api_key
    mode: freedaily

sun:

iqvia:
  zip_code: !secret zipcode

# Nest Temperature
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
    - 'fan'
    - 'target'
    - 'has_leaf'
    - 'online'
    - 'is_using_emergency_heat'
    - 'eta'


# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Spotcast
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

# Hue
light:
  - platform: hue
    host: !secret hue_ip
hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: true

# Xiaomi
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key

# Switches
switch:
  - platform: circadian_lighting
    name: Living Room
    lights_brightness:
      - light.living_room
    min_brightness: 35

  - platform: circadian_lighting
    name: Bedroom
    lights_brightness:
      - light.bedroom
    min_brightness: 35

  - platform: circadian_lighting
    name: Office
    lights_brightness:
      - light.office
    min_brightness: 35

tplink:
  switch:
    - host: !secret tplink_switch_one_ip
    - host: !secret tplink_switch_two_ip
    - host: !secret tplink_switch_three_ip
    - host: !secret tplink_switch_four_ip
    - host: !secret tplink_switch_five_ip

wemo:
  static:
    - !secret wemo_ip

# Text to speech
tts:
  - platform: google_translate
#    service_name: google_say

# Media

# Pi-Hole
pi_hole:
  host: !secret pihole_ip

# Neato Vacuum
neato:
  username: !secret neato_user
  password: !secret neato_password

##########################
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
device_tracker: !include device_tracker.yaml
