homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
      allow_bypass_login: true
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 107
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  country: US

my:

map:
  dark_mode: true

energy:

mqtt:
  discovery: true

zone:
  - name: home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 175

device_tracker:

proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.sean_pixel
      - device_tracker.emily_pixel
    tolerance: 100
    unit_of_measurement: mi

cloud:

mobile_app:

circadian_lighting:

hacs:
  token: !secret hacs_token

system_health:

lovelace:
  #mode: yaml

frontend:
  themes: !include_dir_merge_named themes

config:
http:
  base_url: !secret base_url

#updater:

# Discover some devices automatically
#discovery:
#  ignore:
#    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
#      - switch
    entities:
      - group.sean
      - group.emily
      - light.outside
      - light.living_room
      - light.office
      - light.bedroom
      - climate.downstairs
      - climate.upstairs
      - sensor.downstairs_temperature
      - sensor.upstairs_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.dark_sky_temperature
      - switch.air_freshener
      - switch.bedroom_fan
      - switch.closet_light
      - switch.living_room_fan
      - switch.outside_lights
      - switch.office_fan
      - group.patio_door
      - light.cabinet_lights
      - switch.litter_robot
      - sensor.kitty_throne_waste_drawer

recorder:
  purge_keep_days: 90
  auto_purge: true
  include:
    domains:
#      - switch
    entities:
      - group.sean
      - group.emily
      - light.outside
      - light.living_room
      - light.office
      - light.bedroom
      - climate.downstairs
      - climate.upstairs
      - sensor.downstairs_temperature
      - sensor.upstairs_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.dark_sky_temperature
      - switch.air_freshener
      - switch.bedroom_fan
      - switch.closet_light
      - switch.living_room_fan
      - switch.outside_lights
      - switch.office_fan
      - group.patio_door
      - light.cabinet_lights
      - switch.litter_robot
      - sensor.kitty_throne_waste_drawer

# View all events in a logbook
logbook:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

sun:

# Nest Temperature
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  project_id: !secret nest_project_id
  binary_sensors:
    monitored_conditions:
      - "fan"
      - "target"
      - "has_leaf"
      - "online"
      - "is_using_emergency_heat"
      - "eta"

# Spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Spotcast
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

# Hue
light:
  - platform: hue
    host: !secret hue_ip
  - platform: group
    name: Bedroom Lights
    entities:
      - light.br1
      - light.br2
  - platform: group
    name: Living Room Lights
    entities:
      - light.lr1
      - light.lr2
      - light.lr3
      - light.lr4
      - light.lr5
      - light.lr6
      - light.lr7
      - light.cabinet_lights
  - platform: group
    name: Office Lights
    entities:
      - light.of1
      - light.of2
  - platform: group
    name: Outside Lights
    entities:
      - light.outside_backdoor
hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: true

# Xiaomi
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key


camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points


# Switches
switch:
  - platform: circadian_lighting
    name: Living Room
    lights_brightness:
      - light.living_room
    min_brightness: 50

  - platform: circadian_lighting
    name: Bedroom
    lights_brightness:
      - light.bedroom
    min_brightness: 50

  - platform: circadian_lighting
    name: Office
    lights_brightness:
      - light.office
    min_brightness: 66

tplink:
  switch:
    - host: 192.168.20.51 #Bias Light Switch
    - host: 192.168.20.202 #Bedroom Fan Switch
    - host: 192.168.20.63 #Unused Switch
    - host: 192.168.20.59 #Living Room Fan Switch
    - host: 192.168.20.17 #Air fresehner switch
    - host: 192.168.20.6 #Cabinet Lights

# Text to speech
tts:
  - platform: google_translate
#    service_name: google_say

# Media

wemo:
  static: 
    - 192.168.20.70 #litter robot

media_player:
  - platform: androidtv
    name: Nvidia Shield Pro
    host: 192.168.1.62

##########################
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
input_boolean: !include input_booleans.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
input_select: !include input_select.yaml
# device_tracker: !include device_tracker.yaml
