# Reset volume on all Speakers
- alias: Reset volume on Speakers
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.nesthub
        volume_level: .75
    - service: media_player.volume_set
      data:
        entity_id: media_player.office_speaker
        volume_level: .65
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_speaker
        volume_level: .75
    - service: media_player.volume_set
      data:
        entity_id: media_player.bathroom_speaker
        volume_level: .65

# Set rain audio on repeat every hour
- alias: Repeat Rain Audio
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime_emily
      to: "on"
    - platform: state
      entity_id: input_boolean.bedtime_sean
      to: "on"
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.bedtime_emily
        state: "on"
      - condition: state
        entity_id: input_boolean.bedtime_sean
        state: "on"
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: !secret rain_audio
        media_content_type: audio/mp3

# If rain pauses, start playing again
- alias: Play Rain Audio if Paused
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.bedroom_speaker
      to: "paused"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.bedtime_emily
        state: "on"
      - condition: state
        entity_id: input_boolean.bedtime_sean
        state: "on"
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: !secret rain_audio
        media_content_type: audio/mp3


# Pause Spotify in Office if not occupied for a few minutes
- alias: Pause Office Spotify
  initial_state: off
  trigger:
    - platform: state
      entity_id: sensor.sean_room_location
      from: office
      for:
        seconds: 120
  condition:
    - condition: state
      entity_id: media_player.spotify_sean
      attribute: source
      state: HASTUR
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.spotify_sean