# Bathroom Lights on with Motion
- alias: Bathroom Lights on motion
  initial_state: on
  mode: restart
  trigger:
    platform: state
    entity_id: group.bathroom_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'
    - delay:
        milliseconds: 250
    - service: light.turn_on
      data:
        entity_id: light.bathroom
        brightness_pct: '100'

# Bathroom Lights off without Motion
- alias: Bathroom Lights off no motion
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    - condition: state
      entity_id: group.bathroom_motion
      state: 'off'
      for:
        minutes: 3
    - condition: template
      value_template: "{{ not is_state('media_player.bathroom_speaker', 'playing') }}" # NOT condition
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2
