# Living Room Lights on with Motion
- alias: Living Room Auto Brightness
  initial_state: 'on'
  mode: restart
  trigger:
    - platform: state
      entity_id: group.living_room_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'paused') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'playing') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: "{{ state_attr('switch.circadian_lighting_living_room', 'brightness') | int }}"
    - delay:
        seconds: 1
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: "{{ state_attr('switch.circadian_lighting_living_room', 'brightness') | int }}"

# Auto Living Room Brightness Transition
- alias: Living Room Auto Brightness Transition
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'paused') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv', 'playing') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: "{{ state_attr('switch.circadian_lighting_living_room', 'brightness') | int }}"
        transition: 60

# Living Room Lights off without Motion
- alias: Living Room Lights off no motion
  initial_state: 'on'
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.sean_living_room_presence
        state: 'off'
      - condition: state
        entity_id: input_boolean.emily_living_room_presence
        state: 'off'
      - condition: state
        entity_id: input_boolean.living_room_occupied
        state: 'off'
      - condition: template
        value_template: "{{ not is_state('media_player.plex_living_room_tv', 'paused') }}" # NOT condition
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2
    - delay:
        seconds: 1
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2

# Living Room Lights off without Motion NIGHT TIME
- alias: Living Room Lights off no motion night
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.living_room_motion
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
    - condition: state
      entity_id: group.emily
      state: 'home'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2
    - delay:
        seconds: 1
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2