#### BEDROOM MEDIA ####
# Lights back to full over 7 seconds after media stops
- alias: "Bedroom player stopped"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_bedroom_tv
      from: "playing"
      to: "idle"
  condition:
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: "off"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom
        brightness_pct: "{{ state_attr('switch.circadian_lighting_bedroom', 'brightness') | int }}"
        transition: "15"

# Lights turn off while media is playing
- alias: "Bedroom player playing"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_bedroom_tv
      to: "playing"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom
        transition: "4"

# Lights dim when media is paused
- alias: "Bedroom player paused"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_bedroom_tv
      from: "playing"
      to: "paused"
  condition:
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: "off"
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom
      brightness_pct: "33"
      transition: "7"

# Lights turn off when media is unpaused
- alias: "Bedroom player unpaused"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_bedroom_tv
      from: "paused"
      to: "playing"
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom

# Lights dim to full going from paused to idle
- alias: "Bedroom player pause to idle"
  initial_state: on
  trigger:
    - platform: state
      entity_id: media_player.plex_bedroom_tv
      from: "paused"
      to: "idle"
  condition:
    - condition: state
      entity_id: input_boolean.bedtime_emily
      state: "off"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom
        brightness_pct: "{{ state_attr('switch.circadian_lighting_bedroom', 'brightness') | int }}"
        transition: "10"
