# Auto Office Brightness
- alias: Office Auto Brightness
  initial_state: on
  trigger:
    - platform: state
      entity_id: group.office_motion
      to: "on"
    - platform: state
      entity_id: input_boolean.office_occupied
      to: "on"
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness_pct: "{{ state_attr('switch.circadian_lighting_office', 'brightness') | int }}"
    - service: switch.turn_on
      data:
        entity_id: switch.office_light
    - delay:
        milliseconds: 250
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness_pct: "{{ state_attr('switch.circadian_lighting_office', 'brightness') | int }}"
    - service: switch.turn_on
      data:
        entity_id: switch.office_light

# Auto Office Brightness Transition
- alias: Office Auto Brightness Transition
  initial_state: on
  trigger:
    - platform: state
      entity_id: sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: "home"
    - condition: state
      entity_id: light.office
      state: "on"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.office
        brightness_pct: "{{ state_attr('switch.circadian_lighting_office', 'brightness') | int }}"
        transition: 60

# Turn off Office Lights after one minute of no activity
- alias: Turn office lights without motion one min
  initial_state: on
  trigger:
    platform: time_pattern
    minutes: "/3"
  condition:
    - condition: state
      entity_id: input_boolean.sean_office_presence
      state: "off"
    - condition: state
      entity_id: input_boolean.emily_office_presence
      state: "off"
    - condition: state
      entity_id: group.office_motion
      state: "off"
    - condition: state
      entity_id: input_boolean.office_occupied
      state: "off"
    - condition: template
      value_template: "{{ not is_state('sensor.steam_76561197976250572', 'online') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('sensor.steam_76561198154412871', 'online') }}" # NOT condition
  action:
    - service: light.turn_off
      data:
        entity_id: light.office
        transition: 2
    - service: switch.turn_off
      data:
        entity_id: switch.office_light
    - delay:
        milliseconds: 250
    - service: light.turn_off
      data:
        entity_id: light.office
        transition: 2
    - service: switch.turn_off
      data:
        entity_id: switch.office_light
